# Generated by Django 3.0.6 on 2020-05-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_short', models.CharField(max_length=60)),
                ('question', models.CharField(max_length=450)),
                ('category', models.CharField(choices=[('1', 'Core Concepts'), ('2', 'Configuration'), ('3', 'Multi-Container Pods'), ('4', 'Observability'), ('5', 'Pod Design'), ('6', 'Services and Networking'), ('7', 'State Persistence')], max_length=30)),
                ('submission_date', models.DateTimeField()),
                ('nscontext', models.CharField(max_length=20)),
                ('context', models.CharField(max_length=20)),
                ('workdir', models.CharField(max_length=20)),
            ],
        ),
    ]
